### ISSUE TITLE
App component

### ISSUE THREAD

**Issue by Veri5ied** [Veri5ied/react-chat-app#11]
* Fetches socket server URL from env
* Initiates Socket connection and handle all cases like disconnected, reconnected again so that user can send messages when he/she is back online handles Error scenarios if requests from Axios fails.
* Setup Axios to monitor XHR errors.
* Initiate and listen to socket.
* Fetches User's list from backend to populate.
* Checks if request from axios fails and if it does then shows error modal.
* Shows error if client gets disconnected.
* Establish new connection if reconnected.
* Triggered a notification when message is received.

**Comment by jebitok-dev** [comment]
I would like to contribute
